apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-ih1y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/my-app-1/devfile-sample-code-with-quarkus-ih1y@sha256:60936d1a035934779e30d5392a1906f79a8195deb987f72a0066361087bd83c1
        name: my-java-quarkus
        resources: {}
status: {}
